/**
 * Image Blur Placeholders Config
 *
 * Auto-generated by scripts/generate-blur-placeholders.ts
 * Do not edit manually. Regenerate using: pnpm tsx scripts/generate-blur-placeholders.ts
 */

export interface BlurConfig {
  [imagePath: string]: string;
}

export const IMAGE_BLUR_CONFIG: BlurConfig = {
  "crm-architecture.png": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAADwAQCdASoKAAoABUB8JZQC7AEPAORXgAAA/u3EA8RfnAoAAAA=",
  "erp-architecture.png": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABQAQCdASoKAAoABUB8JQBYdigAAP7u+iqUwIyYpdIeUFuDpGnXlS6Jp8rxu7GaAC2lcAAA",
  "favicon.png": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSFgAAAABcFNt27K86MRMJ3cN4G5B2NiJwOa2QQJNQIFfv+/GQkREiC8xWrzm2aDIBA2KvsgSQ2mLa0hmKHC5iEz/DyJnXFA8wwkUgKJaxPnZtCLon0Nli6s12uUEVlA4IEQAAADQAQCdASoKAAoABUB8JZQCw7ELPxJTIAD+fn/GeEx9HaqBMdHWRKUMTyM4j5E0ml7cgyYos0zRt9R6dB4BDwTplLVAAA==",
  "og-image.png": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4WAoAAAAQAAAACQAABAAAQUxQSDMAAAAAb4d+hY2OhX+Hgpi6q8TDxMOsta+jwr3G2NHGvb29vOfa1u/m19ni3cPn4Ob9/ebh4uIAVlA4ICwAAADQAQCdASoKAAUABUB8JbACdAERAakgAADJAePjTxV8jsMLrNL8XIs7sAAAAA=="
};
