/**
 * Generate Blur Placeholders Script
 *
 * This script generates base64-encoded blur placeholders for images
 * using Sharp. The blur data URLs are stored in a config file for use
 * in the OptimizedImage component.
 *
 * Usage:
 *   pnpm tsx scripts/generate-blur-placeholders.ts
 *   pnpm tsx scripts/generate-blur-placeholders.ts path/to/image.jpg
 */

import sharp from "sharp";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { join, extname, relative, dirname } from "path";
import { fileURLToPath } from "url";
import { pathToFileURL } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, "..");

// Supported image formats (SVG files don't need blur placeholders)
const SUPPORTED_FORMATS = [".jpg", ".jpeg", ".png", ".webp", ".avif"];
const SKIP_FORMATS = [".svg"]; // Skip SVG files as they don't need blur placeholders

interface BlurConfig {
  [imagePath: string]: string;
}

/**
 * Generate a blur placeholder from an image
 */
async function generateBlurPlaceholder(imagePath: string): Promise<string> {
  try {
    const image = sharp(imagePath);
    const metadata = await image.metadata();

    // Resize to 10px width (maintain aspect ratio) for fast processing
    const width = 10;
    const height = metadata.height && metadata.width
      ? Math.round((metadata.height / metadata.width) * width)
      : width;

    const buffer = await image
      .resize(width, height, {
        fit: "cover",
      })
      .webp({ quality: 20 })
      .toBuffer();

    // Convert to base64 data URL
    const base64 = buffer.toString("base64");
    return `data:image/webp;base64,${base64}`;
  } catch (error) {
    console.error(`Error generating blur for ${imagePath}:`, error);
    return "";
  }
}

/**
 * Find all images in a directory recursively
 */
function findImages(dir: string, baseDir: string = dir): string[] {
  const images: string[] = [];

  if (!existsSync(dir)) {
    return images;
  }

  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      // Skip node_modules and .next
      if (entry.name === "node_modules" || entry.name === ".next" || entry.name.startsWith(".")) {
        continue;
      }
      images.push(...findImages(fullPath, baseDir));
    } else if (entry.isFile()) {
      const ext = extname(entry.name).toLowerCase();
      // Skip SVG files and unsupported formats
      if (!SKIP_FORMATS.includes(ext) && SUPPORTED_FORMATS.includes(ext)) {
        const relativePath = relative(baseDir, fullPath).replace(/\\/g, "/");
        images.push(relativePath);
      }
    }
  }

  return images;
}

/**
 * Load existing blur config
 */
function loadBlurConfig(): BlurConfig {
  const configPath = join(PROJECT_ROOT, "lib/v2/image-blur-config.ts");
  if (!existsSync(configPath)) {
    return {};
  }

  try {
    const content = readFileSync(configPath, "utf-8");
    // Extract the config object from the TypeScript file using JSON.parse
    const match = content.match(/export const IMAGE_BLUR_CONFIG: BlurConfig = ({[\s\S]*?});/);
    if (match) {
      // Replace single quotes with double quotes for valid JSON
      const jsonStr = match[1].replace(/'/g, '"');
      return JSON.parse(jsonStr) as BlurConfig;
    }
  } catch (error) {
    // Silently fail - we'll regenerate all blur placeholders
    // This is fine since the script is idempotent
  }

  return {};
}

/**
 * Save blur config to TypeScript file
 */
function saveBlurConfig(config: BlurConfig) {
  const configPath = join(PROJECT_ROOT, "lib/v2/image-blur-config.ts");
  const configContent = `/**
 * Image Blur Placeholders Config
 *
 * Auto-generated by scripts/generate-blur-placeholders.ts
 * Do not edit manually. Regenerate using: pnpm tsx scripts/generate-blur-placeholders.ts
 */

export interface BlurConfig {
  [imagePath: string]: string;
}

export const IMAGE_BLUR_CONFIG: BlurConfig = ${JSON.stringify(config, null, 2)};
`;

  writeFileSync(configPath, configContent, "utf-8");
  console.log(`✅ Saved blur config to ${configPath}`);
}

/**
 * Main function
 */
async function main() {
  const args = process.argv.slice(2);
  const singleImage = args.find((arg) => !arg.startsWith("--"));

  console.log("🎨 Generating blur placeholders...\n");

  const publicDir = join(PROJECT_ROOT, "public");
  const existingConfig = loadBlurConfig();
  const newConfig: BlurConfig = { ...existingConfig };

  let imagesToProcess: string[] = [];

  if (singleImage) {
    // Process single image
    const imagePath = join(publicDir, singleImage);
    if (!existsSync(imagePath)) {
      console.error(`❌ Image not found: ${imagePath}`);
      process.exit(1);
    }
    imagesToProcess = [singleImage];
  } else {
    // Find all images in public directory
    imagesToProcess = findImages(publicDir, publicDir);
    console.log(`Found ${imagesToProcess.length} images to process\n`);
  }

  let processed = 0;
  let skipped = 0;
  let errors = 0;

  for (const imagePath of imagesToProcess) {
    const fullPath = join(publicDir, imagePath);

    // Skip if already in config and file hasn't changed
    if (newConfig[imagePath] && existsSync(fullPath)) {
      console.log(`⏭️  Skipping ${imagePath} (already in config)`);
      skipped++;
      continue;
    }

    console.log(`🔄 Processing ${imagePath}...`);
    const blurDataURL = await generateBlurPlaceholder(fullPath);

    if (blurDataURL) {
      newConfig[imagePath] = blurDataURL;
      processed++;
      console.log(`✅ Generated blur for ${imagePath}`);
    } else {
      errors++;
      console.error(`❌ Failed to generate blur for ${imagePath}`);
    }
  }

  // Save config
  saveBlurConfig(newConfig);

  console.log(`\n✨ Done! Processed: ${processed}, Skipped: ${skipped}, Errors: ${errors}`);
}

// Run if executed directly
if (import.meta.url === pathToFileURL(process.argv[1] || "").href || process.argv[1]?.includes("generate-blur-placeholders")) {
  main().catch((error) => {
    console.error("Fatal error:", error);
    process.exit(1);
  });
}
